{{- $annotations := include "neurox-control-portal.annotations" . | fromYaml -}}
{{- $className := .Values.global.ingress.className -}}
{{- $hostPrimary := include "neurox-control-portal.host.primary" . -}}
{{- $hostsAll := include "neurox-control-portal.host.all" . | split "," -}}
{{- $issuerName := .Values.global.ingress.issuerName -}}
{{- $portalFullName := include "neurox-control-portal.fullname" . -}}
{{- $portalPort := .Values.service.port -}}
{{- $tlsSecretName := include "neurox-control-portal.tlsSecretName" . -}}
{{- $useNeuroxIssuer := (and .Values.global.ingress.useNeuroxIssuer (include "neurox-control-portal.useNeuroxDomain" .)) }}
---
# Default portal ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $portalFullName }}"
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: 'https://$http_host/sso/login?url=$scheme://$http_host$request_uri'
    nginx.ingress.kubernetes.io/auth-url: 'https://$http_host/sso/validate'
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if $useNeuroxIssuer }}
    cert-manager.io/issuer: "{{ $issuerName }}"
  {{- end }}
spec:
  ingressClassName: "{{ $className }}"
  rules:
    - host: {{ $hostPrimary }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $portalFullName }}
                port:
                  number: {{ $portalPort }}
  tls:
    - hosts:
      {{- range $hostsAll }}
        - {{ . }}
      {{- end }}
      secretName: {{ $tlsSecretName }}
---
# Ingress for static assets
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $portalFullName }}-assets"
  annotations:
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if $useNeuroxIssuer }}
    cert-manager.io/issuer: "{{ $issuerName }}"
  {{- end }}
spec:
  ingressClassName: "{{ $className }}"
  rules:
    - host: {{ $hostPrimary }}
      http:
        paths:
          {{- range $prefixPath := list "/assets" "/connector" }}
          - path: {{ $prefixPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $portalFullName }}
                port:
                  number: {{ $portalPort }}
          {{- end }}
          {{- range $exactPath := list "/favicon.ico" "/signin" "/site.webmanifest" }}
          - path: {{ $exactPath }}
            pathType: Exact
            backend:
              service:
                name: {{ $portalFullName }}
                port:
                  number: {{ $portalPort }}
          {{- end }}
  tls:
    - hosts:
      {{- range $hostsAll }}
        - {{ . }}
      {{- end }}
      secretName: {{ $tlsSecretName }}
---
# Redirect from web signout to sso signout
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if $useNeuroxIssuer }}
    cert-manager.io/issuer: "{{ $issuerName }}"
  {{- end }}
    nginx.ingress.kubernetes.io/permanent-redirect: 'https://{{ $hostPrimary}}/sso/logout?url=https%3A%2F%2F{{ $hostPrimary }}'
    nginx.ingress.kubernetes.io/permanent-redirect-code: '301'
  name: "{{ $portalFullName }}-signout"
spec:
  ingressClassName: "{{ $className }}"
  rules:
    - host: {{ $hostPrimary }}
      http:
        paths:
        - path: /signout
          pathType: Exact
          backend:
            # Does not actually route to this service due to redirect annotation
            service:
              name: {{ $portalFullName }}
              port:
                number: {{ $portalPort }}
  tls:
    - hosts:
      {{- range $hostsAll }}
        - {{ . }}
      {{- end }}
      secretName: {{ $tlsSecretName }}
