apiVersion: v1
kind: Service
metadata:
  name: '{{ include "neurox-control-portal.fullname" . }}'
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: '{{ include "neurox-control-portal.fullname" . }}'

