apiVersion: v2
appVersion: 2.0.128
dependencies:
- alias: api
  name: neurox-control-api
  repository: oci://ghcr.io/neuroxhq/helm-charts
  version: 2.215.2
- alias: portal
  condition: portal.enabled
  name: neurox-control-portal
  repository: oci://ghcr.io/neuroxhq/helm-charts
  version: 1.245.0
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.11.3
- alias: manager
  condition: manager.enabled
  name: neurox-control-manager
  repository: oci://ghcr.io/neuroxhq/helm-charts
  version: 1.135.1
- condition: thanos.enabled
  name: thanos
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.13.2
- alias: workload
  name: neurox-workload
  repository: oci://ghcr.io/neuroxhq/helm-charts
  version: 2.0.0
description: A Helm chart for deploying the Neurox Control Cluster
name: neurox-control
version: 2.0.128
