{{- $registrationEnabled := (and .Values.global.ingress.useNeuroxIssuer (include "neurox-control.useNeuroxDomain" .)) }}
{{- if $registrationEnabled }}
# For registration job hook
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: "{{ .Values.global.image.pullSecretName }}"
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-registration'
    verbs:
      - "delete"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-registration'
    verbs:
      - "get"
      - "delete"
  # Cannot gate create by resource name
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "create"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-api'
    verbs:
      - "get"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-registration'
    verbs:
      - "get"
      - "delete"
  # Cannot gate create by resource name
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "create"
  - apiGroups:
      - ""
    resources:
      - "services"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-registration'
    verbs:
      - "get"
      - "delete"
  # Cannot gate create by resource name
  - apiGroups:
      - ""
    resources:
      - "services"
    verbs:
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "2"
  name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
subjects:
  - kind: ServiceAccount
    name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
{{- end }}
# For secrets job hook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
  name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
  name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "2"
  name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
subjects:
  - kind: ServiceAccount
    name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
# For rbac cleanup job hook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  name: '{{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook'
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  name: '{{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook'
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "roles"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
    {{- if $registrationEnabled }}
      - '{{ include "neurox-control.fullname" . }}-registration-job-hook'
      - '{{ include "neurox-control.fullname" . }}-registration-cleanup-job-hook'
    {{- end }}
    verbs:
      - "delete"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "rolebindings"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
      - '{{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook'
    {{- if $registrationEnabled }}
      - '{{ include "neurox-control.fullname" . }}-registration-job-hook'
      - '{{ include "neurox-control.fullname" . }}-registration-cleanup-job-hook'
    {{- end }}
    verbs:
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "serviceaccounts"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
    {{- if $registrationEnabled }}
      - '{{ include "neurox-control.fullname" . }}-registration-job-hook'
      - '{{ include "neurox-control.fullname" . }}-registration-cleanup-job-hook'
    {{- end }}
    verbs:
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "2"
  name: '{{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook'
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook'
subjects:
  - kind: ServiceAccount
    name: '{{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook'
