{{- if and .Values.global.ingress.useNeuroxIssuer (include "neurox-control.useNeuroxDomain" .) }}
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: "{{ .Values.global.image.pullSecretName }}"
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-registration'
    verbs:
      - "delete"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-registration'
    verbs:
      - "get"
      - "delete"
  # Cannot gate create by resource name
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "create"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-api'
    verbs:
      - "get"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-registration'
    verbs:
      - "get"
      - "delete"
  # Cannot gate create by resource name
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "create"
  - apiGroups:
      - ""
    resources:
      - "services"
    resourceNames:
      - '{{ include "neurox-control.fullname" . }}-registration'
    verbs:
      - "get"
      - "delete"
  # Cannot gate create by resource name
  - apiGroups:
      - ""
    resources:
      - "services"
    verbs:
      - "create"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "2"
  name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
subjects:
  - kind: ServiceAccount
    name: '{{ include "neurox-control.fullname" . }}-registration-job-hook'
{{- end }}
