---
apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook'
  namespace: "{{ .Release.Namespace }}"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "9"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
    {{- if .Values.global.scheduling.affinity }}
      affinity: {{ toYaml .Values.global.scheduling.affinity | nindent 8 }}
    {{- end }}
      containers:
        - name: rbac-cleanup
          image: "{{ .Values.register.image.kubectl.repository }}:{{ .Values.register.image.kubectl.tag }}"
          command:
            - /bin/sh
            - -c
            - |
            {{- if and .Values.global.ingress.useNeuroxIssuer (include "neurox-control.useNeuroxDomain" .) }}
              echo "Cleaning up registration job hook rbac resources..."
              kubectl delete rolebinding {{ include "neurox-control.fullname" . }}-registration-job-hook -n ${NAMESPACE}
              kubectl delete role {{ include "neurox-control.fullname" . }}-registration-job-hook -n ${NAMESPACE}
              kubectl delete serviceaccount {{ include "neurox-control.fullname" . }}-registration-job-hook -n ${NAMESPACE}
            {{- end }}

              echo "Cleaning up secrets job hook rbac resources..."
              kubectl delete rolebinding {{ include "neurox-control.fullname" . }}-secrets-job-hook -n ${NAMESPACE}
              kubectl delete role {{ include "neurox-control.fullname" . }}-secrets-job-hook -n ${NAMESPACE}
              kubectl delete serviceaccount {{ include "neurox-control.fullname" . }}-secrets-job-hook -n ${NAMESPACE}

              echo "Cleaning up cleanup job rolebinding..."
              kubectl delete rolebinding {{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook -n ${NAMESPACE}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
    {{- if .Values.global.scheduling.nodeSelector }}
      nodeSelector: {{ toYaml .Values.global.scheduling.nodeSelector | nindent 8 }}
    {{- end }}
      restartPolicy: Never
      serviceAccountName: '{{ include "neurox-control.fullname" . }}-rbac-cleanup-job-hook'
    {{- if .Values.global.scheduling.tolerations }}
      tolerations: {{ toYaml .Values.global.scheduling.tolerations | nindent 8 }}
    {{- end }}
