apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "4"
  name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "4"
  name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "5"
  name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
subjects:
  - kind: ServiceAccount
    name: '{{ include "neurox-control.fullname" . }}-secrets-job-hook'
