{{- $controlFullName := include "neurox-control.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ $controlFullName }}-idp'
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5556
      targetPort: http
      protocol: TCP
      appProtocol: http
    - name: grpc
      port: 5557
      targetPort: grpc
      protocol: TCP
      appProtocol: http
    - name: telemetry
      port: 5558
      targetPort: telemetry
      protocol: TCP
      appProtocol: http
  selector:
    app: '{{ $controlFullName }}-idp'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{ $controlFullName }}-sso'
  name: '{{ $controlFullName }}-sso'
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: '{{ $controlFullName }}-sso'
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ $controlFullName }}-relay-server'
spec:
  selector:
    app: '{{ $controlFullName }}-relay-server'
  ports:
    - protocol: TCP
      port: {{ .Values.relay.service.relayPort }}
      targetPort: 8080
      name: relay
    - protocol: TCP
      port: {{ .Values.global.relay.apiPort }}
      targetPort: 7080
      name: api
