---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "neurox-control.fullname" . }}-idp'
  namespace: "{{ .Release.Namespace }}"
imagePullSecrets:
  - name: "{{ .Values.global.image.pullSecretName }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "neurox-control.fullname" . }}-sso'
  namespace: "{{ .Release.Namespace }}"
imagePullSecrets:
  - name: "{{ .Values.global.image.pullSecretName }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "neurox-control.fullname" . }}-relay-server'
  namespace: "{{ .Release.Namespace }}"
imagePullSecrets:
  - name: "{{ .Values.global.image.pullSecretName }}"
