---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "neurox-control-portal.fullname" . }}'
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: '{{ include "neurox-control-portal.fullname" . }}'
  template:
    metadata:
      labels:
        app: '{{ include "neurox-control-portal.fullname" . }}'
    spec:
    {{- if .Values.global.scheduling.affinity }}
      affinity: {{ toYaml .Values.global.scheduling.affinity | nindent 8 }}
    {{- end }}
      containers:
      - name: '{{ include "neurox-control-portal.fullname" . }}'
        image: '{{ include "neurox-control-portal.image.registry" . }}:{{ default .Chart.AppVersion .Values.image.tag }}'
        imagePullPolicy: '{{ include "neurox-control-portal.image.pullPolicy" . }}'
    {{- if .Values.envOverride.intercomAppId }}
        env:
        - name: INTERCOM_APP_ID
          value: '{{ .Values.envOverride.intercomAppId }}'
    {{- end }}
        ports:
        - containerPort: 80
    {{- if .Values.global.scheduling.nodeSelector }}
      nodeSelector: {{ toYaml .Values.global.scheduling.nodeSelector | nindent 8 }}
    {{- end }}
      serviceAccountName: '{{ include "neurox-control-portal.fullname" . }}'
    {{- if .Values.global.scheduling.tolerations }}
      tolerations: {{ toYaml .Values.global.scheduling.tolerations | nindent 8 }}
    {{- end }}
