{{- $annotations := include "neurox-control-portal.annotations" . | fromYaml -}}
{{- $className := .Values.global.ingress.className -}}
{{- $hostPrimary := include "neurox-control-portal.host.primary" . -}}
{{- $hostsAll := include "neurox-control-portal.host.all" . | split "," -}}
{{- $issuerName := .Values.global.ingress.issuerName -}}
{{- $portalFullName := include "neurox-control-portal.fullname" . -}}
{{- $portalPort := .Values.service.port -}}
{{- $tlsSecretName := include "neurox-control-portal.tlsSecretName" . -}}
{{- $useNeuroxIssuer := (and .Values.global.ingress.useNeuroxIssuer (include "neurox-control-portal.useNeuroxDomain" .)) }}
---
# Default portal ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $portalFullName }}"
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: 'https://$http_host/sso/login?url=$scheme://$http_host$request_uri'
    nginx.ingress.kubernetes.io/auth-url: 'https://$http_host/sso/validate'
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if $useNeuroxIssuer }}
    cert-manager.io/issuer: "{{ $issuerName }}"
  {{- end }}
spec:
  ingressClassName: "{{ $className }}"
  rules:
    - host: {{ $hostPrimary }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $portalFullName }}
                port:
                  number: {{ $portalPort }}
  tls:
    - hosts:
      {{- range $hostsAll }}
        - {{ . }}
      {{- end }}
      secretName: {{ $tlsSecretName }}
---
# Ingress for static assets
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $portalFullName }}-assets"
  annotations:
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if $useNeuroxIssuer }}
    cert-manager.io/issuer: "{{ $issuerName }}"
  {{- end }}
spec:
  ingressClassName: "{{ $className }}"
  rules:
    - host: {{ $hostPrimary }}
      http:
        paths:
          {{- range $prefixPath := list "/assets" "/connector" }}
          - path: {{ $prefixPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $portalFullName }}
                port:
                  number: {{ $portalPort }}
          {{- end }}
          {{- range $exactPath := list "/signin" }}
          - path: {{ $exactPath }}
            pathType: Exact
            backend:
              service:
                name: {{ $portalFullName }}
                port:
                  number: {{ $portalPort }}
          {{- end }}
          {{- range $implementationPath := list "/favicon.ico" "/site.webmanifest" }}
          - path: {{ $implementationPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $portalFullName }}
                port:
                  number: {{ $portalPort }}
          {{- end }}
  tls:
    - hosts:
      {{- range $hostsAll }}
        - {{ . }}
      {{- end }}
      secretName: {{ $tlsSecretName }}
