{{- $controlFullName := include "neurox-control.fullname" . }}
# Required for neurox-control-idp to use Kubernetes CRDs as storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ $controlFullName }}-idp'
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ $controlFullName }}-idp-cluster'
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: '{{ $controlFullName }}-idp'
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: '{{ $controlFullName }}-idp'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ $controlFullName }}-idp'
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["dex.coreos.com"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ $controlFullName }}-idp'
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: '{{ $controlFullName }}-idp'
subjects:
  - kind: ServiceAccount
    namespace: neurox
    name: '{{ $controlFullName }}-idp'
