{{- $hostPrimary := include "neurox-control.host.primary" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "neurox-control.fullname" . }}-idp'
  namespace: "{{ .Release.Namespace }}"
stringData:
  config.yaml: |
    enablePasswordDB: true

    expiry:
      authRequests: "1h"

    grpc:
      reflection: true

    issuer: https://{{ $hostPrimary }}/idp

    oauth2:
      alwaysShowLoginScreen: false
      skipApprovalScreen: true

    staticClients:
      - idEnv: OIDC_CLIENT_ID
        name: "Neurox Single Sign-On"
        redirectURIs:
          - https://{{ $hostPrimary }}/sso/auth
        secretEnv: OIDC_CLIENT_SECRET

    storage:
      type: kubernetes
      config:
        inCluster: true

    connectors:
      - type: oidc
        id: google
        name: Google
        config:
          issuer: https://accounts.google.com
  {{- if has "google" .Values.global.identityProviders.enabled }}
          clientID: $GOOGLE_CLIENT_ID
          clientSecret: $GOOGLE_CLIENT_SECRET
          redirectURI: https://{{ $hostPrimary }}/idp/callback

          scopes:
            - email
            - openid
            - profile

          claimMapping:
            preferred_username: picture

        {{- if .Values.global.identityProviders.google.hostedDomains }}
          providerDiscoveryOverrides:
            authURL: https://accounts.google.com/o/oauth2/v2/auth?hd={{ join "," .Values.global.identityProviders.google.hostedDomains }}
        {{- end }}
  {{- end }}
