---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "neurox-control-api.fullname" . }}'
  namespace: "{{ .Release.Namespace }}"
imagePullSecrets:
  - name: "{{ .Values.global.image.pullSecretName}}"
